---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: default
  labels:
    app: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-service
          image: tomrist9/order-service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/host.docker.internal?currentSchema=orders&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-schema-registry:8081"

          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  selector:
    app: order-deployment
  ports:
    - name: order-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: default
  labels:
    app: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-service
          image: tomrist9/payment-service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/host.docker.internal?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  selector:
    app: payment-deployment
  ports:
    - name: payment-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-deployment
  namespace: default
  labels:
    app: pharmacy-deployment
spec:
  selector:
    matchLabels:
      app: pharmacy-deployment
  template:
    metadata:
      labels:
        app: pharmacy-deployment
    spec:
      containers:
        - name: pharmacy-service
          image: tomrist9/pharmacy-service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/host.docker.internal?currentSchema=pharmacy&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-schema-registry:8081"

          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service
  namespace: default
  labels:
    app: pharmacy-service
spec:
  selector:
    app: pharmacy-deployment
  ports:
    - name: pharmacy-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer-deployment
spec:
  selector:
    matchLabels:
      app: customer-deployment
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer-service
          image: tomrist9/customer-service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/host.docker.internal?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
  labels:
    app: customer-service
spec:
  selector:
    app: customer-deployment
  ports:
    - name: customer-service-port
      protocol: TCP
      port: 8184
  type: LoadBalancer
  loadBalancerIP: ""